#!/bin/bash

# Define the index and other parameters
INDEX="salmon_index"

# List of sample IDs
SAMPLES=("SRRXXX" "SRRXXX" "SRRXXX" "SRRXXX" "SRRXXX" "SRRXXX" "SRRXXX" "SRRXXX")

# Loop through each sample ID
for SAMPLE in "${SAMPLES[@]}"
do
  # Run salmon quant
  salmon quant -i $INDEX -l A -r ${SAMPLE}.trimmed.fastq.gz --validateMappings -o salmon_out/${SAMPLE} --threads 3
  
done

3- ctrl x and save 

4- chmod +x salmon_quant.sh

5- ./salmon_quant.sh
